[package]
name = "modern-russian-dissertation"
version = "0.0.3"
compiler = "0.13.1"
entrypoint = "lib.typ"
repository = "https://github.com/SergeyGorchakov/russian-phd-thesis-template-typst"
authors = ["Sergei Gorchakov", "Georgy Meshcheryakov"]
license = "MIT"
description = "A russian phd thesis template"
keywords = ["thesis", "phd", "vak", "gost", "russian"]
categories = ["thesis"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
